from selenium.webdriver.common.by import By
agree = (By.ID,"com.tencent.mobileqq:id/dialogRightBtn")
click_login = (By.XPATH,"//*[contains(@text,'登录')]")
uid = (By.XPATH,"//*[contains(@content-desc,'请输入QQ号码或手机或邮箱')]")
pwd = (By.ID,"com.tencent.mobileqq:id/password")
login = (By.ID,"com.tencent.mobileqq:id/login")
message_text = (By.ID,"com.tencent.mobileqq:id/ivTitleName")
head = (By.ID,'com.tencent.mobileqq:id/conversation_head')
setting = (By.XPATH,"//*[contains(@content-desc,'设置')]")
user_manager = (By.ID,"com.tencent.mobileqq:id/account_switch")
logout_user = (By.ID,"com.tencent.mobileqq:id/logoutBtn")
makesure_logout = (By.ID,'com.tencent.mobileqq:id/dialogRightBtn')
fail_login = (By.ID,'com.tencent.mobileqq:id/dialogRightBtn')